version: "3"
networks:
  behaving:
    name: behaving

services:
  selenoid:
    networks:
      - behaving
    image: aerokube/selenoid:latest-release
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./var/video:/opt/selenoid/video"
      - "./var/log:/opt/selenoid/logs"

    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./var/video
    command:
      [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-video-output-dir",
        "/opt/selenoid/video",
        "-log-output-dir",
        "/opt/selenoid/logs",
        "-container-network",
        "behaving",
      ]
    ports:
      - "4444:4444"

  web:
    image: nginx
    container_name: web
    networks:
      - behaving
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./tests/www:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./config/ssl/web.pem:/etc/nginx/cert/web.pem
      - ./config/ssl/web-key.pem:/etc/nginx/cert/web-key.pem

  behaving:
    build: ./
    image: behaving.dev
    networks:
      - behaving
    user: behaving
    container_name: behaving
    stdin_open: true
    depends_on:
      - selenoid
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./var/log:/app/var/log
      - ./var/screenshots:/app/var/screenshots
      - ./var/mail:/app/var/mail
      - ./var/sms:/app/var/sms
      - ./var/gcm:/app/var/gcm
      - ./var/downloads:/app/var/downloads
